---
title: "map"
output: html_document
date: "2022-12-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(dplyr)
library(gapminder)
library(highcharter)
library(reactable)
library(tibble)
library(ggplot2)
library(highcharter)

```


```{r}

gapminder <- gapminder %>%
  rename(name = country) %>%
  mutate(name = as.character(name)) %>%
  mutate(name = ifelse(name == 'United States', 'United States of America', name)) %>%
  mutate(name = ifelse(name == 'Congo, Rep.', 'Republic of Congo', name)) %>%
  mutate(name = ifelse(name == 'Congo, Dem. Rep.', 'Democratic Republic of the Congo', name)) %>%
  mutate(name = ifelse(name == 'Korea, Dem. Rep.', 'North Korea', name)) %>%
  mutate(name = ifelse(name == 'Korea, Rep.', 'South Korea', name)) %>%
  mutate(name = ifelse(name == 'Serbia', 'Republic of Serbia', name)) %>%
  mutate(name = ifelse(name == 'Tanzania', 'United Republic of Tanzania', name)) %>%
  mutate(name = ifelse(name == 'Yemen, Rep.', 'Yemen', name)) %>%
  mutate(name = ifelse(name == "Cote d'Ivoire", 'Ivory Coast', name)) %>%
  mutate(name = ifelse(name == "Guinea-Bissau", 'Guinea Bissau', name))


countries <- as.character(sort(unique(gapminder$name)))

```


```{r}

country_fks <- 'Sweden'
continent_fks <- as.character(gapminder$continent[gapminder$name == country_fks])[1]

cont_country_summary <- gapminder %>% 
  filter(
    year == 2007,
    continent == continent_fks
    ) %>% 
  group_by(continent, year) %>% 
  summarise(
    lifeExp   = mean(lifeExp),
    pop       = sum(pop),
    gdpPercap = mean(gdpPercap)
  ) %>% 
  ungroup() %>% 
  bind_rows(
    gapminder %>% 
  filter(
    year == 2007,
    name == 'Sweden'
    )
  ) %>% 
  mutate(name = ifelse(is.na(name), as.character(continent), name)) %>% 
  select(name, lifeExp, pop, gdpPercap) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column('id') %>% 
  setNames(c('id', 'Continent', 'Country')) %>% 
  filter(id != 'name') %>% 
  mutate(
    Continent = round(as.numeric(as.character(Continent)),2),
    Country = round(as.numeric(as.character(Country)),2)
         ) %>% 
  mutate(value = case_when(
    id == 'lifeExp'    ~ round(Country - Continent, 2),
    id == 'pop'        ~ Country / Continent * 100,
    id == 'gdpPercap'  ~ round(Country - Continent, 2)
  )) %>% 
  mutate(value = round(value, 2))
  
cont_country_summary

```




```{r}



col_stops <- data.frame(
  q = c(0.15, 0.4, .8),
  c = c('#55BF3B', '#55BF3B', '#55BF3B'),
  stringsAsFactors = FALSE
)

highchart() %>%
  hc_chart(type = "solidgauge") %>%
  hc_pane(
    startAngle = -90,
    endAngle = 90,
    background = list(
      outerRadius = '100%',
      innerRadius = '60%',
      shape = "arc"
    )
  ) %>%
  hc_tooltip(enabled = FALSE) %>% 
  hc_yAxis(
    stops = list_parse2(col_stops),
    lineWidth = 0,
    minorTickWidth = 0,
    tickAmount = 2,
    min = 0,
    max = 100,
    labels = list(y = 26, style = list(fontSize = "22px"))
  ) %>%
  hc_add_series(
    data = cont_country_summary$value[2],
    dataLabels = list(
      y = -50,
      borderWidth = 0,
      useHTML = TRUE,
      style = list(fontSize = "140px")
    )
  ) %>% 
  hc_size(height = 250) 
# %>% 
#   hc_title(text = '% of Continent Population')


```














```{r}


hchart(gapminder_compare,
       "line",
       hcaes(x = year, y = round(lifeExp, 1), group = name),
       # name = "Continent",
       dataLabels = list(enabled = TRUE, format = "{point.name}")
) %>%
  hc_title(text = 'Life Expectancy by Countries') %>%
  hc_yAxis(title = list(text = "Life Expectancy (Years)")) %>%
  hc_xAxis(title = list(text = NULL))

```


